apiVersion: v1
kind: Pod
metadata:
  name: purple
spec:
  containers:
    - command:
        - sh
        - -c
        - echo The app is running! && sleep 3600
      image: busybox:1.28
      name: purple-container
  # Adding 2 init containers to execute sleep commands
  initContainers:
    - command:
        - sh
        - -c
        - sleep 60
      image: busybox:1.28
      name: warm-up-1
    - command: ["sh", "-c", "sleep 120"]
      image: busybox:1.28
      name: warm-up-2
