---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: test 
spec:
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      role: webserver
      jane: akil
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3]}
  template:
    metadata:
      name: web
      labels:
        role: webserver
        version: v1
        tier: front
        jane: akil
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
            requests:         
              memory: "100Mi"
              cpu: "250m"
            limits:           
               memory: "128Mi"
               cpu: "300m"     
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: test
  labels:
    role: web-service
spec:
  selector:
    role: webserver
  type: NodePort
  ports:
  - port: 80
    nodePort: 32003
