apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: training1-get-pods
subjects:
- kind: User
  name: training1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: get-pods
  apiGroup: rbac.authorization.k8s.io
