---
- name: Install nginx on Ubuntu
  hosts: all
  become: true
  tasks:
   - name: Ensure apt is updated
     apt:
       update_cache: yes
       cache_valid_time: 3600
   - name: Fix broken dependecies
     apt:
       name: "*"
       state: fixed
     changed_when: false
   - name: Wait for aptlock to be released
     shell: "while sudo lsof /var/lib/dpkg/lock; do sleep 5; done"
     changed_when: false
     ignore_errors: true

   - name: Install nginx
     apt:
       name: nginx
       state: present
       install_recommends: yes

